library(stringr) # load stringr library for string manipulation
library(dplyr)   # load dplyr library for data manipulation

data <- readLines("inputs/day7_input.txt") # read in text input as 'data'

size <- integer() # initialize integer for file size
stack <- vector() # initialize vector for directory stack
path <- ''        # initialize string to hold directory path
files <- list()   # initialize list to hold directory path & size

vpop <- function(vector){         # function that takes a vector as an input
  return(vector[-length(vector)]) # and will return the same vector with the
}                                 # last element removed

for(line in data){ # loop through each line in the data
  
  if(str_starts(line, "(?:\\$ cd)")){ # check if line begins with '$ cd'
    
    if(str_ends(line, "/")){ # if the line ends with '/'
      
      # set stack variable to 'root'
      stack = 'root' 
      
      # set the 'root' element in the file list to 0
      files[['root']] = 0 
      
    } else if(str_ends(line, "\\..")){ # if the line ends with '..'
      
      # remove the last element of the stack
      stack = vpop(stack) 
      
    } else if(str_ends(line, "\\w+")){ # if line ends with word characters
      
      # add extracted word to stack
      stack = append(stack, str_extract(line,"[\\S]*$"))
      
      # create filepath string by concatenating the elements in the stack
      path = paste(stack, collapse = ' ') 
      
      if(!any(str_detect(names(files), path))){ # if path not in filename list
        
        # add the path to file name list and initialize size value to 0
        files[[path]] = 0
        
      }
      
    }
    
  } else if(str_starts(line, "^\\d+\\b")){ # if string starts with digits
    
    # extract digits from start of string, store to size variable
    size = str_extract(line, "^\\d+")
    
    # initialize a temporary path variable to hold character values
    tmp.pth = as.character()
    
    for(dir in stack){ # loop through each element in the stack
      
      # add the current element to the temporary path
      tmp.pth = c(tmp.pth, dir)
      
      # create a string by concatenating the elements in the temporary path
      path.name = paste(tmp.pth, collapse = ' ')
      
      # add the size to the value of the current path in the filename list
      files[[path.name]] = files[[path.name]] + as.numeric(size)
    }
    
  }
  
}

# create a dataframe from with a 'dir' column containing the names of each 
# element and a 'size' column that stores the size of the corresponding dir
files.df = data.frame(dir = names(unlist(files)),
                      size = unname(unlist(files)))

# filter the dataframe to only include rows where the 'size' is less than or
# equal to 100000
filter(files.df, size <= 100000) %>%
  summarise(total = sum(size)) # sum the size of filtered dirs to find total

##### PART 2

# this code generated by openai's chatGPT model

# the prompt used: 
# Write R code to find the smallest directory within the files.df dataframe 
# that, if deleted, would ensure the total size of the outermost directory 
# (the 'root' directory) would satisfy the equation 70000000 - root >= 30000000

# find the size of the 'root' directory
root_size <- files.df[files.df$dir == "root", "size"]

# filter the data frame to only include directories that are not the 'root' directory
files.df_filtered <- files.df[files.df$dir != "root", ]

# sort the filtered data frame by size in ascending order
files.df_filtered_sorted <- files.df_filtered[order(files.df_filtered$size), ]

# initialize a variable to hold the smallest directory that satisfies the equation
smallest_directory <- NULL

# loop through each directory in the sorted data frame
for(dir in files.df_filtered_sorted$dir){
  
  # check if deleting the current directory would satisfy the equation
  if(70000000 - (root_size - files.df_filtered_sorted[files.df_filtered_sorted$dir == dir, "size"]) >= 30000000){
    
    # if it does, store the current directory in the smallest_directory variable
    smallest_directory <- dir
    break
    
  }
  
}

# print the smallest directory
print(dsmallest_directory)

# print the size of the smallest directory
print(files.df_filtered_sorted[files.df_filtered_sorted$dir == smallest_directory, "size"])
